sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.4
env:
  - PUPPET_GEM_VERSION="~> 3.3"
  - PUPPET_GEM_VERSION="~> 3.7" FUTURE_PARSER="yes"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
  fast_finish: true
notifications:
  email: false
